/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h> /* memset */
#include <unistd.h> /* close */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f407.h"
#include "helper_gpio.h"

void delay(void)
{
	for(int i = 0; i < 500; i++);
}

int main(void)
{

GPIO_Handle_t GPIOLed, GPIOBtn;

//clear registers
memset(&GPIOLed,0,sizeof(GPIOLed));
memset(&GPIOBtn,0,sizeof(GPIOBtn));

//enable peripheral clock
GPIOD_PCLK_EN();

//initialize pin
GPIOLed.pGPIOx = GPIOD;
GPIOLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
GPIOLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
GPIOLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
GPIOLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

GPIO_Init(&GPIOLed);

//enable peripheral clock
GPIOA_PCLK_EN();

//initialize pin
GPIOBtn.pGPIOx = GPIOA;
GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

GPIO_WriteToOutputPin(GPIOD,GPIO_PIN_NO_12,GPIO_PIN_RESET);
GPIO_Init(&GPIOBtn);

GPIO_IRQInterruptConfig(6, ENABLE);



while(1);


}

void EXTI0_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
}
